### ISSUE TITLE
Python versions

### ISSUE THREAD

**Issue by Snowmanko** [freeipa/zone2dyndb-ldif#2]
Hi, 
I would like to ask which python versions are supported.
In 2.7.6 I got errors like:

Traceback (most recent call last):
  File "./zone2dyndb-ldif.py", line 127, in <module>
    print(n)
  File "./zone2dyndb-ldif.py", line 105, in __str__
    ldifw.unparse(self.dn, convert(self.ldap_obj))
  File "/usr/lib/python2.7/dist-packages/ldif.py", line 196, in unparse
    self._unparseAttrTypeandValue('dn',dn)
  File "/usr/lib/python2.7/dist-packages/ldif.py", line 143, in _unparseAttrTypeandValue
    self._unfoldLDIFLine(': '.join([attr_type,attr_value]))
  File "/usr/lib/python2.7/dist-packages/ldif.py", line 108, in _unfoldLDIFLine
    self._output_file.write(line)
TypeError: unicode argument expected, got 'str'

Thanks.

**Comment by abbra** [comment]
Since https://github.com/freeipa/zone2dyndb-ldif/pull/1 merged, Python 3 is the only supported version.

**Comment by Snowmanko** [comment]
Thanks, I've installed pyldap module with pip3 and now it works as expected!
